### ISSUE TITLE
A bunch of incorrect aggressive removal listed for Safari 9.1.3 only

### ISSUE THREAD

**Issue by othermaciej** [GoogleChrome/confluence#204]
I don't think any of the APIs below were actually removed in Safari 9.1.3, and the catalog seems to be aware that they were present both before and after.

https://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Safari_9.1.3_OSX_10.11.6%22,%22Safari_8.0.8_OSX_10.10.5%22,%22Safari_7.1.8_OSX_10.9.5%22,%22Safari_6.2.8_OSX_10.8.5%22,%22Safari_6.0.5_OSX_10.7.5%22,%22Safari_5.1.9_OSX_10.6.8%22,%22Chrome_57.0.2987.98_OSX_10.11.6%22,%22Firefox_52.0_OSX_10.11%22,%22Edge_14.14393_Windows_10.0%22%5D&releaseOptions=%7B%22Safari_9.1.3_OSX_10.11.6%22:false,%22Chrome_57.0.2987.98_OSX_10.11.6%22:true,%22Firefox_52.0_OSX_10.11%22:true,%22Edge_14.14393_Windows_10.0%22:true%7D&numAvailable=%5B4,5,6,7,8,9%5D&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22

**Comment by RByers** [comment]
@mdittmer Maybe there's some stale data from a previous crawl there still?  I checked a couple and the API catalog does show them present in 8 and 10 but not 9 (eg. `CustomEvent.detail` and `window.indexedDB`).

Looks like just a few and the history isn't as important as the current state, so dropping urgent label.

**Comment by RByers** [comment]
Poking at Safari 10.1.2 I see that properties which are supposed to be on `WebGLRenderingContext.prototype` are actually on an ancestor prototype which isn't exposed on window (`WebGLRenderingContextBasePrototype`).  But I don't see that interface listed in the catalog either.

@mdittmer we walk the whole prototype chain of interface objects we find, right?  Shouldn't we still find these properties somewhere, even if we end up reporting that they're on the wrong interface?

Re-adding urgent in case this represents a more fundamental data issue.

**Comment by mdittmer** [comment]
I'm seeing the same thing. Everything other than `WebGLRenderingContext` APIs are indeed not present in Safari 9.1.

I still need to dig into the code, but my guess is that since `window.WebGLRenderingContext.prototype.__proto__` is not exposed on `window`, the code doesn't know what API to add it to. Of course, this can be fixed. If we find that the shortest path from `window` to `window.Foo(.__proto__ ^ n)` is `window.Foo(.__proto__ ^ n)`, we should add it to `Foo`.

**Comment by othermaciej** [comment]
It seems a priori really unlikely that a property would be present in Safari 8.0.8, missing in Safari 9.1.3 and present in Safari 10.1.2. This is also the only Aggressive Removal claimed for any version of Safari. Like, it's possible than 9.1.3 accidentally dropped a lot of APIs but it seems pretty unlikely. I am really skeptical any of these are real, and I wonder how you tested.

**Comment by RByers** [comment]
Using BrowserStack to poke at Safari 9.1.3 I see there's definitely something weird going on with property enumeration:
```
`indexedDB` in window
> true
Object.getOwnPropertyNames(window).indexOf('indexedDB')
> -1
Object.getOwnPropertyNames(Object.getPrototypeOf(window)).indexOf('indexedDB')
> -1
Object.getPrototypeOf(Object.getPrototypeOf(window))==Object.prototype
> true
```

So this looks similar to #201 where properties exist but don't show up with `getOwnPropertyNames`.  @cdumez, sound familiar by any chance?

**Comment by cdumez** [comment]
Object.getOwnPropertyNames(window).indexOf('indexedDB') returns a valid value (i.e. not -1) in Safari 11.

**Comment by RByers** [comment]
Yes, it's fine now - just seemed broken in Safari 9 only.

**Comment by othermaciej** [comment]
It's totally possible that Object.getOwnPropertyNames had a bug in some Safari 9.x versions but that's pretty far back. Regardless, it doesn't seem helpful to interpret this bug as aggressive removal of a bunch of APIs.

**Comment by RByers** [comment]
I agree it's not helpful, but it's pretty hard to do anything else.  Unless I'm missing something, there's no good generic way for us to discover that these APIs exist without `getOwnPropertyNames` working.

I suppose we could generate a list of candidate APIs (based on what we found in other browsers) and try explicitly probing for each of them rather than relying solely on enumeration.  But I think that would add significant complexity to the architecture.  @mdittmer WDYT?

We could also just make a hard-coded list of the APIs we know weren't actually removed from Safari 9 and probe for those (or even just manually augment the list with them).  That seems like a pretty ugly hack, but would work if it's really valuable to do so.

Any other ideas?

**Comment by RByers** [comment]
Another option is to hack around this for `WebGLRenderingContext` only - that seems to be the main one affecting the graphs.  In that case it does seem like we should be able to discover the properties on the ancestor prototype (`WebGLRenderingContext` does show up in `Object.getOwnPropertyNames(window)`) and copy them down to the right interface.  Understanding why that isn't already working is probably the first priority here (since it could impact other APIs elsewhere too).

**Comment by othermaciej** [comment]
I don't understand the testing approach very well. I would imagine that before claiming something is removed in a release, you could have a double-check test pass that directly checks for its presence regardless of enumeration mechanisms.

This issue makes the Safari aggressive removal graph look weird and bogus. Especially so because there are multiple 9.1.3 data points. So it looks like there was a big time range of heavy aggressive removal, without closer examination.

**Comment by RByers** [comment]
Yeah, I agree it's not ideal.  As I understand it, the current architecture is split into three steps: 
1. For each browser/version/OS, collect a JS object graph dump from the device and save it to cloud storage (this is the time consuming and sometimes unreliable part and so done offline somewhat manually)
2. For each browser/version/OS, process the object graph dump into an API list (this is where the more brittle heuristics happen, so we can tweak and re-run this easily)
3. Use the above API lists to compute the metrics and expose them as catalog data.

So there are benefits to having the code that is actually running on the browser know nothing about what APIs might be "removed" - it's a one-directional pipeline of information.

**Comment by mdittmer** [comment]
So the `WebGLRenderingContext` issue helped me discover a Safari 9.1 peculiarity, and an issue that is definitely a data collection bug.

1. **Not all constructors are constructors**

The source of the issues with `WebGLRenderingContext` is that its constructor is not a function: `typeof WebGLRenderingContext === WebGLRenderingContext instanceof Function === false`.

In order to capture this API accurately, we would need the upstream object graph generator to use a new heuristic identifying "functions and function-like things", and for capturing function names.

In addition, we would need to modify the heuristic for API name detection: it looks for `thePrototype.constructor`, which right now is `Object` on `WebGLRenderingContext.prototype.__proto__`; in cases such as this we would need to remember that we are on the prototype chain of something called "WebGLRenderingContext" and shove properties on to it when `!thePrototype.hasOwnProperty('constructor')`.

2. **Data collection needs to check `thePrototype.hasOwnProperty('constructor')` (via equivalent `object-graph-js` API).

Right now, the check for `thePrototype.constructor` in the Object Graph => API list transform walks the prototype chain. This is probably the wrong thing to do. We should only trust a prototype's constructor to correctly identify the interface when it is an own property.

Filed #210 to track this issue.

**Comment by mdittmer** [comment]
Further investigation has revealed that in Safari 6, 7, 8, `WebGLRenderingContext.prototype.constructor` does exist (without an extra level of indirection to `[...].__proto__` as in Safari 9.1). I think for these earlier releases we are hitting [this code path](https://github.com/GoogleChrome/confluence/blob/master/lib/web_catalog/api_extractor.es6.js#L513) intended for libraries such as `Math` or `console` (and at some point [extended to grab properties from the `.prototype` property](https://github.com/GoogleChrome/confluence/blob/master/lib/web_catalog/api_extractor.es6.js#L517)). That code path is missed once the path looks like `Foo.prototype.__proto__(.APIs)` instead of `Foo.prototype(.APIs)`.

**Comment by foolip** [comment]
If it proves difficult to work around the getOwnPropertyNames issue in Safari 9.x, how would everyone feel about just omitting everything prior to Safari 10? Long time series would be nice, but the actionable stuff is all about what the state during the past year was.

**Comment by mdittmer** [comment]
We get less useful data for metrics that rely on "before the 1-year grace period" if we only have two Safari releases, though.

**Comment by mdittmer** [comment]
The output files from `main/og_to_journal.es6.js` look like #217 will fix the `WebGLRenderingContext` case.

**Comment by mdittmer** [comment]
`CustomEvent.detail` is genuinely missing from `CustomEvent.prototype` in Safari 9.1. It exists in Safari 8 and 10.

**Comment by mdittmer** [comment]
The "Aggressive Removal metric" part of this is fixed in prod. Note cross-referenced outstanding issue.

@othermaciej does this look better? (Of course, properties like `indexedDB` that are covered in #229 still show up in the link you provided.)

**Comment by othermaciej** [comment]
Yes, looks more sensible now.
